name: go test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16', '1.15' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: go test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: upload code coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Markdown autodocs
      - uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          # Optional, defaults to author of the commit that triggered the run
          commit_author: Author <actions@github.com>
          # Optional, defaults to "actions@github.com"
          commit_user_email: actions@github.com
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply automatic changes
          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          #    branch: feature-123
          # Optional output file paths, defaults to '[./README.md]'.
          #    output_file_paths: '[./README.md]'
          # Categories to automatically sync or transform its contents in the markdown files.
          # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
          categories: '[code-block]'

