name: go test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: go test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: upload code coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

